### PR TITLE
Fix builds in Travis-CI

### PR DESCRIPTION
**Pull request by meganemura**
Fix builds to be green.

1. Fix missing nullify in teardown
2. Modify .travis.yml

### CODE REVIEW

**Comment by meganemura** [comment]
@stevepeak Would you please review this?

**Comment by meganemura** [comment]
@stevepeak ping

**Comment by meganemura** [comment]
@stevepeak ping

**Comment by pablofullana** [comment]
Any ETA for this one?

**Comment by meganemura** [comment]
@stevepeak ping

**Comment by meganemura** [comment]
@stevepeak ping

**Comment by meganemura** [comment]
@stevepeak ping

**Comment by meganemura** [comment]
Close in favor of #39

**Pull request closed without merging**
