### PR TITLE
Refactor the reporter a bit and make it grok skipped lines.

### PR DESCRIPTION
**Pull request by coderanger**
So this should be a bit better than what was there but it is having some odd results for me. I tried it out on https://codecov.io/github/poise/poise-service?ref=master and it seems to be showing the full paths as reported by SimpleCov. Maybe this is usually fixed up on the server side for Travis builds?

### CODE REVIEW

**Comment by coderanger** [comment]
Never mind, fixed the relative filenames. Could you nuke the grumpy files on that project? I don't see any way to do it myself.

**Comment by coderanger** [comment]
Also while I am sending nil for the nocov-d lines, they still show as missed?

**Comment by coderanger** [comment]
To continue my "also" train, I tried sending line messages for the skipped lines, but doesn't seem to show correctly.

**Comment by coderanger** [comment]
Any chance you could release this gem?

**Comment by stevepeak** [comment]
Just deployed. Thanks Noah

**Pull request merged**
