### PR TITLE
Support Heroku CI

### PR DESCRIPTION
**Pull request by meganemura**
I think we may be able to support Heroku CI.

refs:
https://docs.codecov.io/reference#upload
https://github.com/codeclimate/test-reporter/pull/305

We can also set 'CODECOV_SLUG' via app.json.

related: #21

### CODE REVIEW

**Comment by meganemura** [comment]
It works.
https://codecov.io/gh/meganemura/pkgstatus/commit/bda26a88da4bcf71683b0e38093b2dba8278a83b/builds

**Comment by meganemura** [comment]
Failing tests is due to #29.

**Comment by meganemura** [comment]
In addition, Heroku CI has a `HEROKU_TEST_RUN_NUMBER` numeric number. But this is undocumented.

**Comment by olmar** [comment]
Any news about this PR?

**Comment by ALexALed** [comment]
@meganemura Any news about this?

**Comment by meganemura** [comment]
In addition, this PR works well with my projects.

**Comment by meganemura** [comment]
@stevepeak ping

**Comment by meganemura** [comment]
@stevepeak ping

**Comment by meganemura** [comment]
@stevepeak ping

**Comment by meganemura** [comment]
@stevepeak ping

**Comment by meganemura** [comment]
@hootener Would you please review this?

**Comment by hootener** [comment]
Merged and deployed to rubygems :+1:

**Comment by meganemura** [comment]
Thanks 😃

**Pull request merged**
